# Generated by Django 6.0.3 on 2026-03-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_alter_product_options_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
