# Generated by Django 6.0.3 on 2026-04-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_alter_product_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reciept',
            field=models.FileField(null=True, upload_to='orders/reciepts/'),
        ),
    ]
